import test,{beforeEach} from 'node:test'
import assert from 'node:assert/strict'
const storage=new Map<string,unknown>();let calls:any[]=[];let handler:(request:any)=>void=()=>{}
;(globalThis as any).uni={getStorageSync:(k:string)=>storage.get(k),setStorageSync:(k:string,v:unknown)=>storage.set(k,structuredClone(v)),removeStorageSync:(k:string)=>storage.delete(k),$emit:()=>{},request:(options:any)=>{calls.push(options);handler(options)}}
import * as api from '../src/services/api'
import * as vault from '../src/services/vault'
import * as receipts from '../src/services/privacy-receipts'
function auth(scope='guardian-A'){vault.saveAuth({accessToken:'test-access',refreshToken:'test-refresh',expiresIn:900,session:{sessionId:'session-A',mode:'GUARDIAN',familyId:'family-A',actorScopeKey:scope,accountScopeKey:'account-A',capabilities:['GUARDIAN']}})}
function success(req:any,data:unknown){req.success({statusCode:200,data:{data,requestId:'r1',serverTime:new Date().toISOString()}})}
beforeEach(()=>{storage.clear();calls=[];auth();handler=req=>success(req,{ok:true})})
test('PATCH uses supported POST transport but original PATCH operation method',async()=>{await api.mutate('PATCH','/families/family-A',{name:'新家庭',expectedVersion:1});assert.equal(calls[0].method,'POST');assert.equal(calls[0].header['X-HTTP-Method-Override'],'PATCH');assert.ok(calls[0].header['Idempotency-Key']);assert.equal(api.currentPending().length,0)})
test('unknown write blocks duplicate and retries the exact original key and payload',async()=>{handler=req=>req.fail({errMsg:'timeout'});await assert.rejects(api.mutate('POST','/families/family-A/children/c/orders',{rewardId:'r',expectedCostPoints:30}),/结果尚未确认/);const op=api.currentPending()[0]!;assert.equal(op.state,'UNKNOWN');await assert.rejects(api.mutate('POST',op.path,{rewardId:'changed'}),/尚未确认/);assert.equal(calls.length,1);handler=req=>req.method==='GET'?success(req,{state:'NOT_OBSERVED',retryWithSameKey:true}):success(req,{order:{id:'original'}});await api.recoverOperation(op);assert.equal(calls[2].header['Idempotency-Key'],op.key);assert.deepEqual(calls[2].data,op.body);assert.equal(api.currentPending().length,0)})
test('successful lookup consumes pending operation without repeating mutation',async()=>{handler=req=>req.fail({});await assert.rejects(api.mutate('POST','/families/family-A/children/c/praises',{points:10}));const op=api.currentPending()[0]!;handler=req=>success(req,{state:'SUCCEEDED',result:{account:{availablePoints:10}}});const recovered=await api.recoverOperation(op);assert.deepEqual(recovered,{account:{availablePoints:10}});assert.equal(calls.length,2);assert.equal(calls[1].method,'GET');assert.equal(api.currentPending().length,0)})
test('scope switch hides pending writes and rejects recovery under another identity',async()=>{handler=req=>req.fail({});await assert.rejects(api.mutate('POST','/families/family-A/children/c/orders',{}));const op=api.currentPending()[0]!;auth('child-A');assert.equal(api.currentPending().length,0);await assert.rejects(api.recoverOperation(op),/原身份/);assert.equal(calls.length,1)})
test('profile write can recover across PROFILE_ONLY to ACCOUNT using account scope',async()=>{handler=req=>req.fail({});await assert.rejects(api.mutate('PUT','/me/profile',{displayName:'家长'}));const op=api.currentPending()[0]!;auth('account-mode');assert.equal(api.currentPending().length,1);handler=req=>success(req,{state:'SUCCEEDED',result:{profile:{}}});await api.recoverOperation(op);assert.equal(api.currentPending().length,0)})
test('stale family response cannot render after switching identity',async()=>{handler=req=>{auth('different-family');success(req,{private:'old family'})};await assert.rejects(api.get('/families/family-A/children'),/身份已切换/)})
test('known validation rejection clears operation so corrected form may retry',async()=>{handler=req=>req.success({statusCode:400,data:{error:{code:'VALIDATION_ERROR',message:'名称太短'},requestId:'v1'}});await assert.rejects(api.mutate('PATCH','/families/family-A',{name:'a'}),/名称太短/);assert.equal(api.currentPending().length,0)})
test('privacy receipt survives logout and contains no household records',()=>{receipts.saveReceipt({requestId:'r1',receiptToken:'private-receipt',type:'DELETE',scope:'SELF_ACCOUNT'});vault.clearAuth();assert.equal(receipts.savedReceipts().length,1);assert.equal(vault.loadAuth(),null);assert.deepEqual(Object.keys(receipts.savedReceipts()[0]!).sort(),['receiptToken','requestId','scope','type'])})
test('simultaneous different payloads never share one upload intent result',async()=>{let waiting:any;handler=req=>{waiting=req};const first=api.mutate('POST','/media/upload-intents',{filename:'first.png'});await assert.rejects(api.mutate('POST','/media/upload-intents',{filename:'second.png'}),/尚未确认/);assert.equal(calls.length,1);success(waiting,{mediaId:'first-only'});assert.deepEqual(await first,{mediaId:'first-only'});assert.equal(api.currentPending().length,0)})
