<script setup lang="ts">
import { ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api } from '../../store';
const kind=ref('DAILY');
const gid=ref(''),items=ref<any[]>([]),loading=ref(false),error=ref(''),cursor=ref(''),more=ref(true);
const date=(v:string)=>new Date(v).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});
function status(c:any){if(['CLAIMED','REJECTED'].includes(c.status)&&Date.now()>=Date.parse(c.expiresAt))return c.status==='REJECTED'?'已截止 · 未通过':'已截止 · 未提交';return ({CLAIMED:'进行中',SUBMITTED:'待审核',REJECTED:'需修改',APPROVED:'已完成'} as Record<string,string>)[c.status];}
async function load(reset=false){if(loading.value)return;loading.value=true;error.value='';try{const data=await api('/groups/'+gid.value+'/me/participations?kind='+kind.value+'&limit=30'+(!reset&&cursor.value?'&cursor='+cursor.value:''));items.value=reset?data.items:[...items.value,...data.items];cursor.value=data.nextCursor||'';more.value=data.hasMore;}catch(e:any){error.value=e.message;}finally{loading.value=false;}}
onLoad(options=>{gid.value=String(options?.groupId||'');kind.value=options?.kind==='LIMITED'?'LIMITED':'DAILY';uni.setNavigationBarTitle({title:kind.value==='DAILY'?'日常记录':'活动记录'});load(true);});
</script>
<template><view class="history-page"><view class="heading"><view><text class="title">我的参与记录</text><text class="hint">记录每一份努力和成长</text></view><button class="link" :disabled="loading" @click="load(true)">刷新</button></view><view v-for="c in items" :key="c.id" class="card"><view class="row"><text class="tag" :class="c.activity?.kind==='LIMITED'?'limited':'daily'">{{c.activity?.kind==='LIMITED'?'限时':'日常'}}</text><text class="state">{{status(c)}}</text></view><text class="name">{{c.activity?.title||'活动'}}</text><text class="hint">{{c.period==='ONCE'?date(c.createdAt):c.period}} · 奖励 {{c.activity?.points||0}} 积分</text><text v-if="c.submission" class="description">完成说明：{{c.submission}}</text><text v-if="c.reviewReason" class="description">审核说明：{{c.reviewReason}}</text><text v-if="['CLAIMED','REJECTED'].includes(c.status)&&Date.now()<Date.parse(c.expiresAt)" class="hint">请返回活动页提交完成，截止 {{date(c.expiresAt)}}</text></view><text v-if="error" class="error">{{error}}</text><text v-if="loading" class="empty">正在读取…</text><button v-else-if="error" class="link bottom" @click="load()">重试</button><text v-else-if="!items.length" class="empty">还没有参与记录，去活动页开启第一次挑战吧。</text><button v-else-if="more" class="link bottom" @click="load()">加载更多</button><text v-else class="empty">已显示全部记录</text></view></template>
<style>
.history-page{max-width:800px;margin:auto;padding:20px 16px calc(24px + env(safe-area-inset-bottom))}.heading,.row{display:flex;align-items:center;justify-content:space-between;gap:12px}.title{font-size:22px;font-weight:700;display:block}.hint{display:block;font-size:12px;color:#8491a6;line-height:1.8;margin-top:6px}.link{color:#426ce0;font-size:13px;min-height:44px;padding:10px}.card{background:white;border:1px solid #e7edf6;border-radius:14px;padding:18px;margin-top:16px}.tag{font-size:11px;font-weight:700;border-radius:6px;padding:5px 8px}.limited{color:#a84d06;background:#fff0db}.daily{color:#4567ab;background:#edf3ff}.state{font-size:12px;color:#657895}.name{font-size:16px;font-weight:600;display:block;margin-top:12px;overflow-wrap:anywhere}.description{display:block;white-space:pre-wrap;overflow-wrap:anywhere;color:#65748b;font-size:13px;line-height:1.8;margin-top:12px}.empty{display:block;text-align:center;padding:30px 10px;font-size:12px;color:#8491a6}.error{display:block;color:#c34a4a;margin-top:16px;font-size:13px}.bottom{display:block;margin:12px auto}
</style>
