<script setup lang="ts">
import {computed,ref,onMounted,onUnmounted} from 'vue'
import {currentPending} from '../services/api'
import {useSession} from '../stores/session'
import {go,back as navigateBack,type RouteName} from '../services/navigation'
const props=withDefaults(defineProps<{title?:string;subtitle?:string;back?:boolean;tab?:string;loading?:boolean;error?:string;busy?:boolean;publicPage?:boolean}>(),{title:'',subtitle:'',back:false,tab:'',loading:false,error:'',busy:false,publicPage:false})
defineEmits<{retry:[]}>();const session=useSession()
const pendingCount=ref(currentPending().length);const refreshPending=()=>{pendingCount.value=currentPending().length};onMounted(()=>{uni.$on('operations:changed',refreshPending);uni.$on('auth:changed',refreshPending)});onUnmounted(()=>{uni.$off('operations:changed',refreshPending);uni.$off('auth:changed',refreshPending)})
const tabs=computed(()=>session.isChild?[['today','今天','sun'],['wishes','心愿','gift'],['growth','成长','sprout']]:[['home','首页','home'],['plans','计划','list'],['rewards','奖励','gift'],['family','家庭','family']])
function topAction(){if(session.isDelegated)go('pin',{purpose:'exit'});else if(session.isChild)go('account');else go('contexts')}
</script>
<template><view class="app-shell" :class="{ 'has-tabs': tab, 'child-ui':session.isChild }"><view v-if="!publicPage" class="identity"><button v-if="back" class="text-button back-button" @tap="navigateBack">‹ 返回</button><view v-else class="identity-name"><text class="brand-dot">✦</text><view><text class="identity-title">{{session.isChild?'我的积乐圈':session.family?.family.name||'积乐圈'}}</text><text class="caption">{{session.isChild?(session.isDelegated?'家长共用设备':'我的微信账号'):session.isGuardian?'家长模式':'我的微信账号'}}</text></view></view><button class="text-button small" @tap="topAction">{{session.isChild?(session.isDelegated?'家长入口':'账号设置'):'切换家庭'}}</button></view><view class="page-body"><view v-if="title" class="page-heading"><text class="eyebrow">{{session.isChild?'每一点努力，都算数':'一起约定，慢慢长大'}}</text><text class="page-title">{{title}}</text><text v-if="subtitle" class="muted body-copy">{{subtitle}}</text></view><view v-if="session.isFamilyReadOnly" class="notice read-only-banner">家庭已归档，业务记录只读。</view><view v-if="loading" class="loading-box"><view class="skeleton"/><view class="skeleton short"/><text>正在加载…</text></view><view v-if="error" class="notice error" role="alert"><text>{{error}}</text><button class="text-button" @tap="$emit('retry')">重试读取</button></view><view v-if="pendingCount" class="notice warning"><text>有{{pendingCount}}次操作还需要确认结果。</text><button class="text-button" @tap="go('recovery')">查询原操作</button></view><slot/></view><view v-if="tab" class="bottom-nav"><button v-for="item in tabs" :key="item[0]" :class="{active:tab===item[0]}" @tap="go(item[0] as RouteName,{},true)"><text class="nav-symbol">{{item[2]==='home'?'⌂':item[2]==='gift'?'◇':item[2]==='list'?'☷':item[2]==='family'?'♧':item[2]==='sun'?'☀':'♧'}}</text><text>{{item[1]}}</text></button></view></view></template>
