<script setup lang="ts">
import {computed,reactive} from 'vue'
import type {UploadItem} from '../services/types'
import {chooseLocalImages,uploadImage,pollImage,mediaUrl,type MediaScope} from '../services/media'
import {mutate} from '../services/api'
import PrivateImage from './PrivateImage.vue'
const props=withDefaults(defineProps<{modelValue:UploadItem[];scope:MediaScope;max?:number;avatar?:boolean;disabled?:boolean}>(),{max:3,avatar:false,disabled:false});const emit=defineEmits<{ 'update:modelValue':[UploadItem[]] }>()
const count=computed(()=>props.modelValue.length)
async function choose(source:'camera'|'album'){if(props.disabled)return;try{const files=await chooseLocalImages(props.avatar?1:props.max-count.value,source);const additions=files.map(f=>reactive(f));const list=props.avatar?additions:[...props.modelValue,...additions];emit('update:modelValue',list);for(const item of additions){try{await uploadImage(item,props.scope)}catch{/* each tile displays its own retry state */}}}catch(e){if(e instanceof Error)uni.showToast({title:e.message,icon:'none'})}}
async function remove(item:UploadItem){item.status='DELETED';emit('update:modelValue',props.modelValue.filter(i=>i.localId!==item.localId));if(item.mediaId)try{await mutate('DELETE',`/media/${item.mediaId}`,{},'移除未提交照片')}catch{/* expired or already removed files have no business effect */}}
async function retry(item:UploadItem){try{if(item.status==='PROCESSING')await pollImage(item);else if(item.localPath)await uploadImage(item,props.scope);else await choose('album')}catch{/* item carries its own error */}}
async function preview(item:UploadItem){const url=item.localPath||(item.mediaId?await mediaUrl(item.mediaId):'');if(url)uni.previewImage({urls:[url]})}
</script>
<template><view class="media-upload"><view class="row between"><text class="field-label">{{avatar?'上传头像（必填）':'完成照片（选填）'}}</text><text class="caption">{{count}}/{{max}}</text></view><view class="media-grid" :class="{single:avatar}"><view v-for="(item,index) in modelValue" :key="item.localId" class="media-tile"><view @tap="preview(item)"><image v-if="item.localPath" :src="item.localPath" mode="aspectFill"/><PrivateImage v-else :media-id="item.mediaId" size="180rpx"/><text class="caption">{{item.status==='READY'?'已准备好':item.status==='UPLOADING'?`上传中 ${item.progress}%`:item.status==='PROCESSING'?'正在处理':item.status==='DELETED'?'已过期':item.status==='FAILED'?'上传失败':'等待上传'}}</text></view><button v-if="!disabled" class="remove-image" @tap="remove(item)" :aria-label="`移除第${index+1}张图片`">×</button><text v-if="item.error" class="field-error">{{item.error}}</text><button v-if="['FAILED','PROCESSING','DELETED'].includes(item.status)&&!disabled" class="text-button" @tap="retry(item)">重试 / 查询</button></view></view><view v-if="!disabled&&(count<max||avatar)" class="upload-actions"><button class="secondary" @tap="choose('album')">{{avatar?'选择头像':'从相册选择'}}</button><button class="secondary" @tap="choose('camera')">拍照</button></view><text class="caption upload-help">{{avatar?'头像可为你喜欢的插画，不必是真人照片。':'仅本人及有权限的家长可见。草稿照片保留24小时，首次正式提交后保留180天。'}} JPEG / PNG / WebP，每张不超过10 MiB。</text><text v-if="modelValue.some(x=>x.status!=='READY')" class="field-error">请等待图片准备好；失败照片可以重试或移除。</text></view></template>
