<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api, useApp, uuid } from '../../store';
const app=useApp(),gid=ref(''),groupName=ref(''),myMemberId=ref(''),ready=ref(false);
const kind=ref('DAILY'),mode=ref('activity'),day=ref(''),today=ref(''),report=ref<any>(null),loading=ref(false),error=ref(''),expanded=ref('');
const selected=ref<any>(null),decision=ref('APPROVE'),reason=ref(''),busy=ref(false),pending=ref<any>(null);
let epoch=0;
function state(c:any){if(!c)return '未参与';if(['CLAIMED','REJECTED'].includes(c.status)&&Date.now()>=Date.parse(c.expiresAt))return c.status==='REJECTED'?'已截止 · 未通过':'已截止 · 未提交';return ({CLAIMED:'进行中',SUBMITTED:'待审核',REJECTED:'需修改',APPROVED:'已完成'} as Record<string,string>)[c.status];}
const groups=computed(()=>{const d=report.value;if(!d)return [];return (mode.value==='activity'?d.activities:d.members).map((g:any)=>{const rows=(mode.value==='activity'?d.members:d.activities).map((item:any)=>{const a=mode.value==='activity'?g:item,m=mode.value==='activity'?item:g,c=d.claims.find((x:any)=>x.activityId===a.id&&x.memberId===m.id);return {id:item.id,title:mode.value==='activity'?m.displayName:a.title,claim:c?{...c,memberName:m.displayName,activityTitle:a.title}:null,status:state(c),applicable:!!c||a.kind==='DAILY'||Date.parse(m.createdAt)<Date.parse(a.endsAt)};}).filter((r:any)=>r.applicable);return {id:g.id,title:g.title||g.displayName,rows,completed:rows.filter((r:any)=>r.claim?.status==='APPROVED').length,waiting:rows.filter((r:any)=>r.claim?.status==='SUBMITTED').length};});});
async function load(){if(!ready.value)return;const current=++epoch;loading.value=true;error.value='';report.value=null;try{const r=await api('/groups/'+gid.value+'/activity-progress?kind='+kind.value+'&date='+day.value);if(current===epoch)report.value=r;}catch(e:any){if(current===epoch)error.value=e.message;}finally{if(current===epoch)loading.value=false;}}
watch([kind,day],()=>{expanded.value='';load();});
function chooseDay(e:any){if(!busy.value&&!pending.value)day.value=e.detail.value;}
function review(c:any){if(pending.value||busy.value)return;selected.value=c;decision.value='APPROVE';reason.value='';error.value='';}
async function send(){if(busy.value)return;if(!pending.value){if(decision.value==='REJECT'&&!reason.value.trim()){error.value='请填写驳回原因';return;}pending.value={userId:app.user?.id,groupId:gid.value,claim:selected.value,path:'/groups/'+gid.value+'/activity-claims/'+selected.value.id+'/review',body:{decision:decision.value,reason:reason.value.trim(),expectedVersion:selected.value.version},key:uuid()};uni.setStorageSync('pj-progress-pending',pending.value);}busy.value=true;error.value='';try{await api(pending.value.path,'POST',pending.value.body,pending.value.key);pending.value=null;uni.removeStorageSync('pj-progress-pending');selected.value=null;uni.showToast({title:'审核已保存',icon:'success'});await load();}catch(e:any){error.value=e.message;if(!e.uncertain&&e.status<500){pending.value=null;uni.removeStorageSync('pj-progress-pending');}}finally{busy.value=false;}}
function submit(){if(pending.value){send();return;}uni.showModal({title:decision.value==='APPROVE'?'通过并发放积分？':'驳回修改？',content:decision.value==='APPROVE'?'确认完成后，积分将自动计入该成员账户。':'成员可在活动截止前修改并重新提交。',success:r=>{if(r.confirm)send();}});}
onLoad(async(options)=>{gid.value=String(options?.groupId||'');try{if(!app.user)await app.init();const d=await api('/groups/'+gid.value+'/dashboard');if(!d.admin)throw new Error('仅管理员可查看完成情况');groupName.value=d.group.name;myMemberId.value=d.membership.id;today.value=d.activityDate;day.value=d.activityDate;ready.value=true;const saved=uni.getStorageSync('pj-progress-pending');if(saved&&saved.userId===app.user?.id&&saved.groupId!==gid.value){ready.value=false;throw new Error('另一群组有待确认的审核，请返回该群组的完成情况页重试确认');}if(saved&&saved.userId===app.user?.id){pending.value=saved;selected.value=saved.claim;decision.value=saved.body.decision;reason.value=saved.body.reason;}await load();}catch(e:any){error.value=e.message;}});
</script>
<template>
 <view class="progress-page"><text class="group-name">{{groupName}}</text><text class="title">完成情况</text>
 <view v-if="ready" class="controls"><view class="segmented"><button :disabled="busy||!!pending" :class="{active:kind==='DAILY'}" @click="kind='DAILY'">日常</button><button :disabled="busy||!!pending" :class="{active:kind==='LIMITED'}" @click="kind='LIMITED'">限时</button></view><view class="filter-row"><view class="segmented"><button :class="{active:mode==='activity'}" @click="mode='activity';expanded=''">按活动</button><button :class="{active:mode==='member'}" @click="mode='member';expanded=''">按成员</button></view><picker v-if="kind==='DAILY'" mode="date" :value="day" :end="today" @change="chooseDay"><view class="date">{{day}} ▾</view></picker><button class="link" @click="load">刷新</button></view><text class="hint">{{kind==='DAILY'?'按所选日期查看每位成员的日常完成情况。':'查看限时活动的完成情况。'}}点击展开详情并审核。</text></view>
 <text v-if="error" class="error">{{error}}</text><text v-if="loading" class="hint">正在读取…</text>
 <template v-else><view v-for="g in groups" :key="g.id" class="card"><button class="card-heading" @click="expanded=expanded===g.id?'':g.id"><view class="grow"><text class="strong">{{g.title}}</text><text class="hint">已完成 {{g.completed}} / {{g.rows.length}} · 待审核 {{g.waiting}}</text></view><text class="link">{{expanded===g.id?'收起':'展开'}}</text></button><template v-if="expanded===g.id"><view v-for="r in g.rows" :key="r.id" class="record"><view class="row"><text class="strong grow">{{r.title}}</text><text class="badge">{{r.status}}</text></view><text v-if="r.claim?.submission" class="description">完成说明：{{r.claim.submission}}</text><text v-if="r.claim?.reviewReason" class="hint">审核说明：{{r.claim.reviewReason}}</text><button v-if="r.claim?.status==='SUBMITTED'" class="primary" :disabled="busy||!!pending||r.claim.memberId===myMemberId" @click="review(r.claim)">{{r.claim.memberId===myMemberId?'等待其他管理员审核':'审核'}}</button></view><text v-if="!g.rows.length" class="hint">暂无适用记录</text></template></view><text v-if="ready&&!groups.length&&!error" class="hint empty">该分类或日期暂无活动记录</text></template>
 <view v-if="selected" class="overlay"><view class="dialog"><text class="subtitle">审核活动</text><text class="strong">{{selected.activityTitle}} · {{selected.memberName}}</text><scroll-view scroll-y class="submission"><text class="description">{{selected.submission}}</text></scroll-view><view class="segmented"><button :disabled="busy||!!pending" :class="{active:decision==='APPROVE'}" @click="decision='APPROVE'">通过并发积分</button><button :disabled="busy||!!pending" :class="{active:decision==='REJECT'}" @click="decision='REJECT'">驳回修改</button></view><textarea v-model="reason" :disabled="busy||!!pending" maxlength="200" class="reason" :placeholder="decision==='REJECT'?'填写驳回原因（必填）':'审核说明（选填）'"/><text v-if="error" class="error">{{error}}</text><view class="row"><button class="secondary grow" :disabled="busy||!!pending" @click="selected=null">取消</button><button class="primary grow" :disabled="busy" @click="submit">{{busy?'正在保存…':pending?'重试确认':'确认审核'}}</button></view></view></view>
 </view>
</template>
<style>
.progress-page{padding:20px 16px calc(24px + env(safe-area-inset-bottom));max-width:900px;margin:auto}.group-name,.title,.hint,.strong,.description,.error{display:block}.group-name{color:#8793a7;font-size:12px}.title{font-size:24px;font-weight:700;margin:5px 0 22px}.segmented{display:flex;background:#eaf0fc;border-radius:10px;padding:4px;gap:4px}.segmented button{padding:10px 12px;min-height:40px;font-size:13px;border-radius:8px;flex:1;white-space:nowrap;color:#687992}.segmented .active{background:#fff;color:#3564ed;font-weight:600}.filter-row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:12px}.date{background:white;border-radius:8px;padding:12px;font-size:12px}.hint{font-size:12px;color:#8490a3;line-height:1.7;margin-top:8px}.link{color:#426ce0;font-size:12px;min-height:40px;display:flex;align-items:center}.card{background:white;border:1px solid #e7ecf5;border-radius:14px;padding:16px;margin-top:14px}.card-heading,.row{display:flex;gap:12px;align-items:center;width:100%;text-align:left}.grow{flex:1;min-width:0}.strong{font-weight:600;overflow-wrap:anywhere}.record{border-top:1px solid #edf0f6;padding:16px 0}.record:first-child{margin-top:12px}.badge{font-size:11px;color:#617391;flex-shrink:0}.description{font-size:13px;line-height:1.8;color:#65748b;white-space:pre-wrap;overflow-wrap:anywhere;margin:12px 0}.primary,.secondary{min-height:44px;padding:11px 14px;border-radius:9px;font-size:13px}.primary{background:#3564ed;color:white}.secondary{background:#edf1fa;color:#596b86}.record .primary{margin-top:12px}.error{color:#c24e4e;font-size:12px;line-height:1.8;margin:12px 0}.empty{padding:30px;text-align:center}.overlay{position:fixed;inset:0;background:#14274666;display:flex;align-items:center;justify-content:center;padding:16px;z-index:100}.dialog{background:white;border-radius:18px;padding:22px;width:100%;max-width:460px;max-height:85vh;overflow-y:auto}.subtitle{display:block;font-size:20px;font-weight:700;margin-bottom:16px}.submission{max-height:160px}.reason{box-sizing:border-box;background:#f5f7fc;border:1px solid #e8edf5;padding:12px;width:100%;height:100px;border-radius:10px;font-size:14px;margin:16px 0}
</style>
